# Generated by Django 5.0.6 on 2024-06-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbsignup',
            old_name='firstname',
            new_name='fullname',
        ),
    ]
